name: Expexp
options:
  minimumXcodeGenVersion: 2.30.0
targets:
  Expexp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.expexp
        INFOPLIST_FILE: App/Info.plist
        SWIFT_VERSION: 5.9
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
